### ISSUE TITLE
RFC 8617 compliance

### ISSUE THREAD

**Issue by flowerysong** [flowerysong/OpenARC#7]
OpenARC needs to be reviewed to ensure that it is compliant with the requirements published in RFC 8617, since the TDP's development momentum died before publication.

Known issues:
- [x] "The maximum number of ARC Sets that can be attached to a message is 50.": 2d450997221830ee8fd0b1a4665610c57dab2c3b
- [x] "In the case of a failed Authenticated Received Chain, the header fields included in the signature scope of the AS header field b= value MUST only include the ARC Set header fields created by the MTA that detected the malformed chain, as if this newest ARC Set was the only set present.": #6
- [x] "ARC-related header fields (ARC-Authentication-Results, ARC-Message-Signature, and ARC-Seal) MUST NOT be included in the list of header fields covered by the signature of the AMS header field.": #8
- [x] "_OPTIONAL_: Determine the "oldest-pass" value from the ARC Set by validating each prior AMS beginning with N-1": #13 
- [x] The ABNF definitions of the headers require that the instance tag (`i=1`) be the first thing in the header. Generation is compliant, but we do not check for this during validation.: bac50cf54b24198fac33dad029a82e418f5f99ec
- [x] "In all ARC header fields, the d= and s= tags can contain U-labels.": #12 
- [x] "The AAR header allows UTF-8 in the same places that Authentication-Results does": 9d864f763f91729ed6b912971cff74e4cc61fbe3
- [x] "Note especially that the DKIM "h" tag is NOT allowed [in AS] and, if found, MUST result in a cv status of "fail": 0b190b94efdd72cde402adcab89f17a4d3be9abc

Unknown issues: Unknown. Maybe nothing?

**Comment by flowerysong** [comment]
All divergences from the RFC that I was able to identify have been addressed.
