### ISSUE TITLE
TDP issues and PRs

### ISSUE THREAD

**Issue by flowerysong** [flowerysong/OpenARC#9]
PRs:
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/91~~: superseded by 207e5856f7d3d08b9011140eb397487eda539690
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/103~~: outdated
- [x] https://github.com/trusteddomainproject/OpenARC/pull/116
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/120~~: no
- [x] https://github.com/trusteddomainproject/OpenARC/pull/141
- [x] https://github.com/trusteddomainproject/OpenARC/pull/144
- [x] https://github.com/trusteddomainproject/OpenARC/pull/145
- [x] https://github.com/trusteddomainproject/OpenARC/pull/154
- [x] https://github.com/trusteddomainproject/OpenARC/pull/158
- [x] https://github.com/trusteddomainproject/OpenARC/pull/159
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/160~~: mismatch between description and code, unclear what problem this is attempting to address.
- [x] https://github.com/trusteddomainproject/OpenARC/pull/161
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/166~~: based on wrong branch, mix of unrelated changes
- [x] https://github.com/trusteddomainproject/OpenARC/pull/167
- [x] https://github.com/trusteddomainproject/OpenARC/pull/168
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/170~~: duplicate of bbe5279d721c3820e04b62e434552893d66847b5
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/171~~: superseded by 0676227216f69bb52a4da2e52faf1978062b1fd7
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/173~~: superseded by 63fd6e8880c33f906737e9afd9093df747cca101
- [x] ~~https://github.com/trusteddomainproject/OpenARC/pull/176~~: superseded by 9dc8658366b9b3cadbed09754fdf1a7e5cd61e47 and 63fd6e8880c33f906737e9afd9093df747cca101
- [x] https://github.com/trusteddomainproject/OpenARC/pull/177
- [x] https://github.com/trusteddomainproject/OpenARC/pull/178
- [x] https://github.com/trusteddomainproject/OpenARC/pull/179
- [x] https://github.com/trusteddomainproject/OpenARC/pull/180

Issues:
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/21~~: the ValiMail test suite is dead and nothing has taken its place, our tests don't currently have a reason they would need this
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/49~~: mailing list references have been removed
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/65~~: failure is expected without #5, core dump is not but is also not replicable
- [x] https://github.com/trusteddomainproject/OpenARC/issues/66: last user report was that Google verification worked
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/72~~: configs with and without InternalHosts are tested by the test suite, and do not crash
- [x] https://github.com/trusteddomainproject/OpenARC/issues/74: last user report was that it was fixed
- [x] https://github.com/trusteddomainproject/OpenARC/issues/75: #6
- [x] https://github.com/trusteddomainproject/OpenARC/issues/87: #11 fixes generation of signatures with simple header canonicalization, but it's very hard to find another piece of software capable of generating these signatures to check if validation is still wrong in some way (everyone else seems to hardcode relaxed.) The ValiMail test suite examples currently pass but are unsuitable for ongoing use because they predate several hard requirements in the spec.
- [x] https://github.com/trusteddomainproject/OpenARC/issues/97: probably fixed by 4601503aab35548475d31eaac1fb07ef07602148, there were some paths where things weren't freed that I addressed.
- [x] https://github.com/trusteddomainproject/OpenARC/issues/98: fixed in Beta1
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/101~~: bug had already been fixed before report was opened
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/102~~: uninteresting
- [x] https://github.com/trusteddomainproject/OpenARC/issues/111: 839052db247ec3bf87925dcd94194e038bcb9103
- [x] https://github.com/trusteddomainproject/OpenARC/issues/113: fixed
- [x] https://github.com/trusteddomainproject/OpenARC/issues/118: 3cb51002044e03a9556a7e2c5e27ad4b69461a45
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/122~~: I'm not convinced this is a useful configuration for ARC signers, I'm not going to prioritize implementing it.
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/131~~: the reported AR headers are invalid, so OpenARC is correct to report that they're invalid.
- [x] https://github.com/trusteddomainproject/OpenARC/issues/132: #5 
- [x] https://github.com/trusteddomainproject/OpenARC/issues/134: 0676227216f69bb52a4da2e52faf1978062b1fd7
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/135~~: uninteresting
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/136~~: duplicate of 136
- [x] https://github.com/trusteddomainproject/OpenARC/issues/137: 3ff7b30c531582d002c8273c508ce69da056cf41
- [x] https://github.com/trusteddomainproject/OpenARC/issues/142: c2344f0a99ee75fa87df41e7b189f22d340a84b2
- [x] https://github.com/trusteddomainproject/OpenARC/issues/143: 95421678cca7df404029f0c60542e0211256da53 and 52b28e96612e470e06c70f710a3193950161b454 (more comprehensive application of quoting)
- [x] https://github.com/trusteddomainproject/OpenARC/issues/146: #10 
- [x] https://github.com/trusteddomainproject/OpenARC/issues/147: duplicate of 111
- [x] https://github.com/trusteddomainproject/OpenARC/issues/149: last user report was that Zoho verification worked
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/150~~: uninteresting
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/151~~: uninteresting
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/156~~: duplicate of 49
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/157~~: uninteresting
- [x] https://github.com/trusteddomainproject/OpenARC/issues/162: I'm going to assume this is something like b50efaaf3ee857583fa6606fbd928f26c2af8e63
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/163~~: the reported AR headers parse fine under both old and updated AR parsing
- [x] ~~https://github.com/trusteddomainproject/OpenARC/issues/164~~: user configuration issue
- [x] https://github.com/trusteddomainproject/OpenARC/issues/169: bbe5279d721c3820e04b62e434552893d66847b5
- [x] https://github.com/trusteddomainproject/OpenARC/issues/172: 63fd6e8880c33f906737e9afd9093df747cca101
- [x] https://github.com/trusteddomainproject/OpenARC/issues/174: 9dc8658366b9b3cadbed09754fdf1a7e5cd61e47 and 63fd6e8880c33f906737e9afd9093df747cca101

**Comment by flowerysong** [comment]
All open issues and PRs from https://github.com/trusteddomainproject/OpenARC have been reviewed and either addressed or rejected.

**Comment by lquidfire** [comment]
Thank you for doing this mountain of work!

The Archlinux wiki now includes [a link](https://wiki.archlinux.org/title/OpenARC#Installation) to this OpenARC fork.

**Comment by thegushi** [comment]
FlowerySong, this is great work, and we may pick up your fork and push it into here if you're okay with this -- I see no reason for duplication of effort, but not having community confusion is a good thing.  Are you open to this?
